fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix --show-fixes lambda_ stacks
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        entry: ruff format lambda_ stacks
        language: system
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest -v -s
        language: system
        always_run: true
        pass_filenames: false
